### PR TITLE
20230311 卡牌修改（4）卡牌新增（9）

### PR DESCRIPTION
**Pull request by fraloow**

### CODE REVIEW

**Comment by Pippow** [comment]
This looks really ambitious, thanks for the work! What's the reasoning behind Saessenthesis? Some of us feel that she's still a meme and very niche so we were wondering.

**Comment by fraloow** [comment]
> This looks really ambitious, thanks for the work! What's the reasoning behind Saessenthesis? Some of us feel that she's still a meme and very niche so we were wondering.

1. The original version of Saessenthesis was like this, and I hope to restore its original design purpose and effect.
2. The current effect of Saessenthesis is actually a very radical change. Compared with the effect of discarding the entire hand, which may bring in larger point gains within one turn, this effect is dangerous and affects the discard system of Skellige. It may increase the design and balance difficulty of discard-related cards in the future, such as the new card "an craite warlord", which may perform strongly due to its impact.
3. I don't think that being niche means being weak and needing modification. Any game has niche cards, and these cards will experience new changes one day due to new cards and new environments.

**Comment by Pippow** [comment]
> > This looks really ambitious, thanks for the work! What's the reasoning behind Saessenthesis? Some of us feel that she's still a meme and very niche so we were wondering.
> 
> 1. The original version of Saessenthesis was like this, and I hope to restore its original design purpose and effect.
> 2. The current effect of Saessenthesis is actually a very radical change. Compared with the effect of discarding the entire hand, which may bring in larger point gains within one turn, this effect is dangerous and affects the discard system of Skellige. It may increase the design and balance difficulty of discard-related cards in the future, such as the new card "an craite warlord", which may perform strongly due to its impact.
> 3. I don't think that being niche means being weak and needing modification. Any game has niche cards, and these cards will experience new changes one day due to new cards and new environments.

Thanks for the reply!

1. Yes original version was like this, it was changed because it was an unplayable meme card
2. Yes the change is very big indeed. The card has some synergy with big alchemy decks and Alba Spearmen, but most importantly with the new warlord, yes and an craite longships. But so far it doesn't look broken: the Saessenthesis player pays a price in terms of consistency, as you will inevitabely discard good cards, for instance having a warlord in hand is terrible, and not having sassenthesis early is terrible because you loose value on it, and as the game progresses, you risk discarding more warlords or good cards. Furthermore, while impressive, the optimal scenario is only 7 discard procs (you play 2 ships before). 7 might seem a lot, but bear in mind that Sukrus is 5 procs on dire wolf warrior, and can be spammed with sigdrifa, decoy, restore for 5 procs each. What I want to say is that Saessenthesis is not even that essential to the deck (which is not that strong by the way), so unless there are new discard buffs or cards planned I'd suggest leaving Sassenthesis as it is currently.
3. I completely agree with you. Although in this case it is weak, here are its stats since the Discard buff: Number of Games: 93 Wins: 33 Losses: 60 Draws: 0 Winning Rate: 35.48

I just wanna stress out that I really like the other changes you have planned, and that the Sassenthesis nerf is not a big issue, just a fun card that I don't think needs nerfing, but I could live without it.

**Comment by Pippow** [comment]
Palmerin will be really good in Nilfgaard Soldiers, probably autoinclude. The fact that you can protect the slave infantry is very strong, but at the same time, if you play palmerin first, you will miss out on the buffs on the 4 slave infantry not yet spawned, so it looks balanced. Really looking forward to this!

**Pull request merged**
