### PR TITLE
language 

### PR DESCRIPTION
**Pull request by kajtek14102**
- remove promoted cards
- fixed order in language files
- making all copies of language files identical
- fixing "new kalkstein" name in polish
- includes script that made those changes - might be useful in future for people updating language files

### CODE REVIEW

**Comment by Pippow** [comment]
Hurray! Thanks for the work.

**Comment by iceshoesss** [comment]
* LegacyGwent\src\Cynthia.Card.Unity\src\Cynthia.Unity.Card\Assets\Resources\Locales
* LegacyGwent\src\Cynthia.Card.Unity\src\Cynthia.Unity.Card\Assets\StreamingFile\Locales
* LegacyGwent\src\Cynthia.Card\src\Cynthia.Card.Server\bin\Debug\netcoreapp3.0\Locales
What do these three documents effect?
I only modified this one file at a time
**src\Cynthia.Card\src\Cynthia.Card.Server\Locales**

**Comment by kajtek14102** [comment]
Basically editing that is enough, because client checks for server language files on every start, but if it doesn't find it it (this happens when u run it locally) it uses different files. It causes some inconvenience in testing mainly.
TBH I'm not exacly sure its not like i understand the code, but thats one thing i know is happening

**Comment by neal2018** [comment]
> Basically editing that is enough, because client checks for server language files on every start, but if it doesn't find it it (this happens when u run it locally) it uses different files. It causes some inconvenience in testing mainly.
> TBH I'm not exacly sure its not like i understand the code, but thats one thing i know is happening

yeah your understanding is correct

**Pull request merged**
