### PR TITLE
rain nerf 2- WIP

### PR DESCRIPTION
**Pull request by Pippow**
- Vabjorn: deal 2 damage to an enemy,if it is already damaged,destroy it instead,or REPEAT deal 2 damage until it damaged.
- Crow Clan Druid: spawn a crow RIGHT side.
- Svalblod: 11 - > 9

### CODE REVIEW

**Comment by Pippow** [comment]
@The-last-Iris
I have a question about Vabjorn. Since you're always taking option number 2 in the case the unit you target is not damaged
wouldn't it be simpler and more straightforward to make him
"select a unit, if it is damaged, destroy it, otherwise damage it by 2 unitil it is damaged"
I ask because wih Neal and Kajtek we've been trying to avoid unnecessary "choose one" cards
like I did recently with Detlaff Higher vampire

also, should he go back to 11 strength?

**Comment by The-last-Iris** [comment]
> @The-last-Iris I have a question about Vabjorn. Since you're always taking option number 2 in the case the unit you target is not damaged wouldn't it be simpler and more straightforward to make him "select a unit, if it is damaged, destroy it, otherwise damage it by 2 unitil it is damaged" I ask because wih Neal and Kajtek we've been trying to avoid unnecessary "choose one" cards like I did recently with Detlaff Higher vampire
> 
> also, should he go back to 11 strength?

Yes,select a unit, if it is damaged, destroy it, otherwise damage it by 2 unitil it is damaged.This is better.And he should go back to 11.Somehow,I have noticed that GRVV from discard
 said the new Vabjorn will be powerful with axeman/ derran,maybe we should make it 4?
I mean select a unit, if it is damaged, destroy it, otherwise damage it by 4 unitil it is damaged.

**Comment by The-last-Iris** [comment]
And the Sig and Ulle,I would like to hear the voice from discard.

**Comment by Pippow** [comment]
@The-last-Iris the update is functionnal and could be merged. For the moment I have only done the English translation, I won't be able to code until monday, maybe @kajtek14102 can finish the translation.

**Comment by The-last-Iris** [comment]
> @The-last-Iris the update is functionnal and could be merged. For the moment I have only done the English translation, I won't be able to code until monday, maybe @kajtek14102 can finish the translation.

Alright,I'll finish the Chinese translation here.
Vabjorn: 11战力，选择一个敌方单位，如果其已经受伤，则直接摧毁它，否则对其造成2点伤害直至其受伤。
Crow Clan Druid: 回合结束时，若同排没有乌鸦，则在右侧生成一个乌鸦。

**Comment by kajtek14102** [comment]
Vabjorn
Rozmieszczenie: Wybierz jednostke. Jeśli jest zraniona zniszcz ją. Jeśli nie zadawaj 2pkt obrażeń aż będzie zraniona
Crow druid
Name: Adeptka Klanu Kruka
Rozmieszczenie: Na koniec tury, jeśli w tym rzędzie nie ma wrony stwórz wrone po prawej stronie (Wrona; 2 siły; Zemsta: Zadaj 3pkt obrażeń losowemu wrogowi)

Also there is mistake in Vabjorn english text - unitil instead of until.
Sorry for this form, but that's all I have time for today. I nobody is able to put it in code just make it in english as I'm working on refreshing polish version anyway

**Comment by Pippow** [comment]
@The-last-Iris @kajtek14102 thanks a lot guys for the help, it's done: the Russian translation will be done separately, as we're working on a bigger patch for the Russian language

**Comment by Pippow** [comment]
@neal2018 do you have an idea why the build failed? It worked before I updated the locales files (which should hardly break anything?) and builds fine locally.

**Comment by neal2018** [comment]
@Pippow I just rerun a few job and it pass. I think it is just unstable

**Pull request merged**
