### PR TITLE
Aguara and Vrihedd Neophyte not boosting spies

### PR DESCRIPTION
**Pull request by kajtek14102**
-disabled boosting disloyal cards in hand (as we did for different cards before) for Aguara and Neophyte
-Fixed neophyte description to match its behaviour - it boost 2 cards most to the left
-adjusted English text - Chinese still needed

### CODE REVIEW

**Comment by neal2018** [comment]
@Pippow What is your opnion on this change? I do not think is necessary though

**Comment by Pippow** [comment]
> @Pippow What is your opnion on this change? I do not think is necessary though

Me and the other reviewers thought that for consistency all random handbuff cards shouldn't be able to target silver spy. But I agree in practice it won't change almost anything.

**Comment by kajtek14102** [comment]
> @Pippow What is your opnion on this change? I do not think is necessary though

Its obviously very small change - I made it mostly for consistency with other cards since we changed other in the past - those are 2 last card that can buff spies in hand. Also those are obviously not very good cards so buffing them little bit cant hurt. I dont think buffing spy in hand is fun rewarding gameplay - especially with aguara. By the way do you remember in gwent open andy buffing yaevin to 20? yes that is what we are trying to avoid
image

Difficult part is Vrihedd Neophyte - should it be random or left side of hand? I have no idea tbh but it cant stay like it was - buffing left and saying otherwise. If you don't like it buffing left side, changing is to random is easy (i think smb just forgot to .mess() thb first time they coded it) but we need  behavior consistent with text. Is it in Chineese?

**Comment by neal2018** [comment]
> @Pippow for consistency all random handbuff cards shouldn't be able to target silver spy

But this PR changes for all disloyal unit, not only silver? Also is there any other random handbuff cards able to target silver spy?


> @kajtek14102 Difficult part is Vrihedd Neophyte

I do agree with you. It is very likely that someone just forget to code `mess`. I think we should change to random to keep consistent with open beta. What is your thought?

**Comment by kajtek14102** [comment]
Yes according to my best knowledge - those are the last cards.
I can change it to just "silver spy", but I think there is no need too, and before we changed many cards to buff only loyal so I think its best for consistency. only card it makes difference for in scoia is Iris and i don't know why would you play that - and if you do you deserve no buff on her for beeing brave :)
As for mess - doesn't matter to me, but i know @Pippow preffered one without randomness.
image
image

**Comment by Pippow** [comment]
> Yes according to my best knowledge - those are the last cards. I can change it to just "silver spy", but I think there is no need too, and before we changed many cards to buff only loyal so I think its best for consistency. only card it makes difference for in scoia is Iris and i don't know why would you play that - and if you do you deserve no buff on her for beeing brave :) As for mess - doesn't matter to me, but i know @Pippow preffered one without randomness. image image

If the 2 of you prefer randomness I'd go for it for nostalgia's sake. I thought it was an intentional rework from QQ honestly ^^

**Comment by kajtek14102** [comment]
So what's the status? As before I'm fine with both options :)

**Comment by kajtek14102** [comment]
@neal2018 
So I updated it according to what we agreed on on discord.

List of changes:
-Aguara not boost only loyals in hand
-Vrihed neophyte now boost 2 random loyal, instead of two leftmost (which we agree was a bug)

**Pull request merged**
