### PR TITLE
Prevents Iorveth from buffing spy in-hand

### PR DESCRIPTION
**Pull request by Pippow**
Prevents Iorveth from buffing spy in-hand.

Small quality of life fix that was requested many many times by different people, including some ex-reviewers.

### CODE REVIEW

**Comment by neal2018** [comment]
We also need to change card description?

**Comment by Pippow** [comment]
> We also need to change card description?

You're absolutely right, will do it asap.Thanks

**Comment by Pippow** [comment]
@neal2018 so I did the translations, but only in the "locales", i.e. I didn't touch the chinese descriptions in the GwentMap file. What's their purpose? I guess they serve to power that bot you got on QQ. I'm asking, because 1) I can't read a word of Chinese so I'm not sure I'm the best person to handle that (and I have proofreaders for other languages, not for this one) 2) it requires to bump the gwentmap version and I'm not sure how that works depending on what gets merged first.

**Comment by neal2018** [comment]
Yes, it serves the bot in qq community .

The gwentmap version need to be updated even if we only change locales json files. Just need to increase by one.

**Comment by Pippow** [comment]
> Yes, it serves the bot in qq community .
> 
> The gwentmap version need to be updated even if we only change locales json files. Just need to increase by one.

thanks. I updated the gwentmap file, I suppose "non-spying" is translated as 非间 as it is the way it's translated in vrihedd dragoon ^^ Should be ready.

**Pull request merged**
