### PR TITLE
bug fixes

### PR DESCRIPTION
**Pull request by Pippow**
- giant's belt is now an item and not a tactic
- tactical advantage cannot be resurected by renew anymore
- Spotter buff rounds up instead of down, as described in the original PR.

### CODE REVIEW

**Comment by Pippow** [comment]
@the-last-iris was there anything else?

**Comment by The-last-Iris** [comment]
> @The-last-Iris was there anything else?

Sorry for these days non-reply,there is sth wrong with my VPN.
Nekker Swarm can be triggered if you have a bigger Ogriod than your opponent,even if you have a bigger such as Toad prince than your own Ogriod,it is not the same as the description.

**Comment by Pippow** [comment]
> > @The-last-Iriswas there anything else?
> 
> Sorry for these days non-reply,there is sth wrong with my VPN. Nekker Swarm can be triggered if you have a bigger Ogriod than your opponent,even if you have a bigger such as Toad prince than your own Ogriod,it is not the same as the description.

Hi, this behaviour is intended, the correct English description is "On turn end, if no ennemy is stronger than the strongest ogroid ally, reduce the counter of the first copy of this unit by 1. When it reaches 0 summon self on a random row and Boost a random ally by 1." I suggest updating the Chinese description.

**Comment by Pippow** [comment]
@The-last-Iris when you said godess of justice, you actually meant land of a thousand fables right? I don't know if the godess of justice is even in the game.

**Comment by The-last-Iris** [comment]
> you actually meant land of a thousand fables right
Screenshot_20241203_183255_cynthia diy card

**Comment by Pippow** [comment]
> > you actually meant land of a thousand fables right
> > Screenshot_20241203_183255_cynthia diy card

perfect, I fixec it in a dirty way, just excluded it from the cards Renew can target.

**Pull request merged**
