### PR TITLE
Update en.json

### PR DESCRIPTION
**Pull request by NPC-YFY**

### CODE REVIEW

**Comment by kajtek14102** [comment]
That is wrong description - at least in polish and in english. Cintran medic can target suport units. Unless its edit prepared for some update that im not aware of, but if so - please contact me on discord for polish translation
image

**Comment by Pippow** [comment]
> That is wrong description - at least in polish and in english. Cintran medic can target suport units. Unless its edit prepared for some update that im not aware of, but if so - please contact me on discord for polish translation image

A nerf is indeed planned to prevent the Cintrian Field Medic from targeting supports, it is meant as a nerf of the NR spallas deck as you won't be able to cycle reaver scouts anymore. I coded it according to YFY's instructions, but was too lazy to make the language updates. The PR for the nerf is not merged yet.

**Comment by NPC-YFY** [comment]
Yes, as you said, this is for the changes that are planned to be implemented. The code changes are in the PR proposed by Pippow (thanks again). At the moment I'm thinking about the timing of the implementation, so it hasn't been merged into the project yet.

**Comment by NPC-YFY** [comment]
Yes. As you said, this is for the changes that are planned to be implemented. The code changes are in the PR proposed by Pippow (thanks again). At the moment I'm thinking about the timing of the implementation, so it hasn't been merged into the project yet.

**Comment by NPC-YFY** [comment]
Yes. As you said, this is for the changes that are planned to be implemented. The code changes are in the PR proposed by Pippow (thanks again). At the moment I'm thinking about the timing of the implementation, so it hasn't been merged into the project yet.

**Comment by kajtek14102** [comment]
ok. here is corect text for PL version:
"Info": "Rozmieszczenie: Wtasuj przyjazną brązową jednostkę nie będącą wsparciem do Twojej talii i zagraj losową brązową jednostkę z talii.",
Should i make separate pull request or can you edit this somehow to avoid confusion? I just want it to be implemented at the same time to not wait for serwer reset after update

**Comment by NPC-YFY** [comment]
> ok. here is corect text for PL version: "Info": "Rozmieszczenie: Wtasuj przyjazną brązową jednostkę nie będącą wsparciem do Twojej talii i zagraj losową brązową jednostkę z talii.", Should i make separate pull request or can you edit this somehow to avoid confusion? I just want it to be implemented at the same time to not wait for serwer reset after update

Thanks for your kind help! I will edit my pull request right now to make it correct.

**Pull request merged**
