### PR TITLE
Ogroids

### PR DESCRIPTION
**Pull request by Pippow**
Approved Changes

- Nekker Swam:
  *  "Bronze ogroid- 2 str- counter 2
  *  On turn end, if no ennemy is stronger than the strongest ogroid ally, reduce the counter of the first copy of this unit by 1. When it reaches 0 summon self on a random row and Boost a random ally by 1."
  *  art: https://i.imgur.com/EACfNnE.png
- Ogre warrior
  *  13 str Bronze:
  *  On turn end, damage self by half on turn end if you don't have the higest unit
  *  art: https://i.imgur.com/EeWHibb.png
- Giant's Belt:
  *  Silver Special, item
  *  "Boost an ally by its base Power,if it is an Ogroid, strengthen it by 2 before."
  *  art: https://i.imgur.com/fRKzz6a.png
- Cloud Giant
  *  "Gold - 10 Power - Ogroid - Resilience
  *  Deploy: if you control the highest unit, gain Immunity. If you don't, loose Immunity. On turn start repeat Deploy ability."
  *  Art: https://cdnb.artstation.com/p/assets/images/images/010/289/035/large/krassimir-mercier-cloudgiantgwentfinal.jpg?1523619481

Changes to evaluate

- Phooca
- 7 str Bronze, Ogroid:
  *  if another ogroid on your board is the highest unit, boost self by 2 on turn end
- art: https://gwent.one/en/card/202837
- Old Speartip.
  *  Reasoning: Both versions are among the worst cards in the game, and are played by nobody (80 times played in the entire 2024 combining both cards, 40% WR for both). We think the asleeep effect can stay the same if we add more ogroids, but for the awake version we need a rework. The 5 of us would really like to see back the closed beta version where it alternated between asleep and awake forms, and transfer the effect of old speartip asleep on a new art, more fitting to be the centerpiece of an ogroid deck: King Churn
  *  Old Speartip: Asleep - Silver 4 Power - Ogroid Deploy: Boost all other units on this row by 1. At the end of your turn, if the opposite row has equal or more than 5 units, transform self into Old Speartip: Awake and trigger it's Deploy ability.
  *  Old Speartip: Awake - Silver8 Power - OgroidDeploy: Damage all units on the opposite row by 1At the end of your turn, if the opposite row has fewer than 5 units, transform self into Old Speartip: Asleep and trigger it's Deploy ability.
- King Chrum:
  *  Same effect as Old Speartip Asleep
  *  art: https://i.imgur.com/j4V43FT.png
- Ice Giant
  *  It's a shame this card doesn't work with bridge troll into foglet, would be a solid core. Also here are the stats of entire 2024 Number of games: 102 WR 32%: nobody plays it and it's bad.
  *  Suggested rework: 6 str - boost self by 4 for any frost or fog on the opposite side of the board
- ~~Tugo the Elder~~

### CODE REVIEW

**Comment by Pippow** [comment]
@The-last-Iris The approved cards have been coded, can you please help me with Chinese translation? Thanks!

Also upon testing I took the liberty of reducing the strengthen effect of Giant's belt to 2 because its value was quite high.

**Comment by The-last-Iris** [comment]
Chinese translation:
Nekker Swam:(card name:水生孽鬼）计数2：回合结束时如果你拥有最高战力单位且是食人魔，位于牌组顺序最靠前的水生孽鬼计数-1，当计数为0时从卡组召唤自身到随机排，并随机增益友方单位1点。
Ogre warrior:(card name:食人魔战士) 回合结束时，如果未控制最高战力单位，则对自身造成一半战力的伤害。
Giant's Belt:(card name:巨人腰带)使一名友方单位获得等同于其基础战力的增益，如果该单位是食人魔，则先强化2点。
Cloud Giant:(card name:云顶巨人)坚韧。部署：如果你拥有最高战力单位，则获得免疫，否则失去免疫。回合开始时重复部署效果。

**Comment by Pippow** [comment]
> Chinese translation: Nekker Swam:(card name:水生孽鬼）计数2：回合结束时如果你拥有最高战力单位且是食人魔，位于牌组顺序最靠前的水生孽鬼计数-1，当计数为0时从卡组召唤自身到随机排，并随机增益友方单位1点。 Ogre warrior:(card name:食人魔战士) 回合结束时，如果未控制最高战力单位，则对自身造成一半战力的伤害。 Giant's Belt:(card name:巨人腰带)使一名友方单位获得等同于其基础战力的增益，如果该单位是食人魔，则先强化2点。 Cloud Giant:(card name:云顶巨人)坚韧。部署：如果你拥有最高战力单位，则获得免疫，否则失去免疫。回合开始时重复部署效果。

Thank you!

**Comment by kajtek14102** [comment]
PL text :)

Rój Nekkerów
"Na koniec tury, jeśli żaden przeciwnik nie jest silniejszy niż Twój najsilniejszy Ogroid, zmniejsz licznik pierwszej kopii tej jednostki w Twojej talii o 1. Gdy licznik osiągnie 0, przyzwij tę jednostkę na losowy rząd i Wzmocnij losowego sojusznika o 1."

Ogr Wojownik
"Na koniec tury, jeśli nie kontrolujesz najsilniejszej jednostki, zadaj sobie obrażenia równe połowie swojej siły."

Pas Olbrzyma
"Wzmocnij sojusznika o jego bazową Siłę. Jeśli to Ogroid, najpierw Ulepsz go o 2."

Gigant z Chmur
"Rozmieszczenie: Jeśli kontrolujesz najsilniejszą jednostkę, zyskaj Odporność. Jeśli nie, utrać Odporność. Na początku tury powtórz efekt Rozmieszczenia.\nWytrzymałość."

**Comment by Pippow** [comment]
@The-last-Iris @kajtek14102 thank you to both of you, translations are done, PR is ready to merge.

**Comment by Pippow** [comment]
@The-last-Iris hi, everything is ready for the new patch, ogroids and new client. With Neal we wanted to do a release and a ranked reset this weekend, are you ok with that?

**Comment by The-last-Iris** [comment]
> @The-last-Iris hi, everything is ready for the new patch, ogroids and new client. With Neal we wanted to do a release and a ranked reset this weekend, are you ok with that?

yes,that is reasonable.

**Comment by The-last-Iris** [comment]
@Pippow the belt should be an item,now it's a tactic.By the way,the Renew can choose Goddess of Justice.Maybe you can fix that.

**Comment by Pippow** [comment]
> @Pippow the belt should be an item,now it's a tactic.By the way,the Renew can choose Goddess of Justice.Maybe you can fix that.

Thanks for pointing it out. I will look into the Godess of Justice topic

**Pull request merged**
