### PR TITLE
diy服2023年3月13日调整

### PR DESCRIPTION
**Pull request by lwr511**
增强：
杰洛特：15->17，（ai1降低新星比例）
操作者：5->7，
法兰：7->9，
弗妮希尔突击队： 6->8
希里：6->9,无护甲,
特莉丝：打5->7，
贝克尔的黑暗之镜：不超过10->13点，
米薇：增益4->5，
军旗手：己方除了召唤之外的所有打出士兵都会触发
神灯：位于墓地时最后的愿望多1个选项，

新卡：
融雪 中立有机：随机使1个友军单位获得2点增益。重复一次。本回合中每打出过1张牌便额外重复1次。

bug怪兽大间谍计时没归零
bug攻城大师触发被锁的机械单位
bug黑暗之境会在结算伤害之前选择增益单位
bug家族诗人没法选金银单位

### CODE REVIEW

**Comment by Pippow** [comment]
I feel the swap archetype is already very strong, especially hyperthin versions with lady of lake, maybe those buffs are a bit too much, for instance feign death into double swap elf into double commandos will be 28pts (33 with Eitnhe) and thins 2. The Geralt buff looks pretty high too, for 22pts officers. I'd suggest tuning it down a bit. Otherwise great work, looks exciting!

**Comment by lwr511** [comment]
First of, feign death should take the blame along side with Eitnhe. With this buff of commando I might finally be able to nerf the card or the combe with Eitnhe. Second, I wouldn't worry too much about 22pts officers, it's already 20pts and easy target for control or reset. I have thought about 7pts and 16pts version but that won't make much impact to the environment. I'm watching the environment data closely. Anything went wrong there is always the next patch (●'◡'●)

**Comment by lwr511** [comment]
> 

First of, feign death should take the blame along side with Eitnhe. With this buff of commando I might finally be able to nerf the card or the combe with Eitnhe. Second, I wouldn't worry too much about 22pts officers, it's already 20pts and easy target for control or reset. I have thought about 7pts and 16pts version but that won't make much impact to the environment. I'm watching the environment data closely. Anything went wrong there is always the next patch (●'◡'●)

**Comment by Pippow** [comment]
Still think it's a bit strong, but it sure looks fun and as you said we can always nerf that later. I'm looking forward  to see this combined with the fix to allow you to swap cards in empty decks.

**Review by neal2018 — APPROVED** [review]

**Pull request merged**
