### PR TITLE
Bug Fix - Plumard

### PR DESCRIPTION
**Pull request by Pippow**
Hi, this PR attempts to fix several bugs that affect the Plumard card and make it work according to the description:

"When a Vampire Ally destroys a unit, Summon a copy of self on a random row. When a different Vampire Ally on the same row  Drains, Drain the same Target by one”

Also I snuck in a few improvements for the Russian translation.

### CODE REVIEW

**Comment by Pippow** [comment]
Also I realise the way I made plumard come out of Detlaff Higher vampire's destroy effect is a bit dirty as I figured it is the only vampire that can kill without damaging or consuming, so I fixed it directly in Detlaff's code. Is it ok? Might pose an issue if we add other destroy vampires later (we would need to do the same for them).

**Comment by neal2018** [comment]
katakan & detlaff should not trigger this ability in my opinion

**Comment by neal2018** [comment]
I think it is fine for hardcoding Detlaff for now, because I can't think of a better solution :(

**Comment by Pippow** [comment]
> katakan & detlaff should not trigger this ability in my opinion

Thanks. One last thing, is the row supposed to be random? Code said yes and description says it should spawn on the destroyed unit row. It matters because plumards get a lot stronger if you can get them on the same row.

**Pull request merged**
