### PR TITLE
Rain Nerf

### PR DESCRIPTION
**Pull request by Pippow**
- siren:return to 'play rain then ressurect'
- Primal Savagery: damage a non-cultist ally by 3 ,and then look at 2 random bronze cultisst, play 1 and strengthen it by 1.
- Nerf the Berserker Marauder from 9 to 7 and give it back the ability to buff twice for a unit that is both cursed and damaged.
- Raging Bear: reduce to 13
- Svalblod: Damage all loyal units in your hand and deck by 2, then Strengthen them by 2. Move any cards with 2 power or lower from your deck to your graveyard. If it was in your hand, set it's power to 1 instead.

### CODE REVIEW

**Comment by The-last-Iris** [comment]
After really heated argument in QQ,we think flaminca should stay current version.And if this nerf is not enough,we can adjust them later.
And Primal Savagery: damage a NON-CULTIST ally 3 damage,and then look at 2 random bronze cultist, play 1 and strengthen it 1.
Raging Bear: reduce to 13
By the way,you can code Svalblod: Damage all loyal units in your hand and deck by 2, then Strengthen them by 2. Move any cards with 2 power or lower from your deck to your graveyard. If it was in your hand, set it's power to 1 instead. 
So the adjustments in #569 are half passed.Corsair,Dimun Warship,Craite Whaler are non-diy cards,we perfer not to adjust them except them are too weak or too powerful.

**Comment by Pippow** [comment]
> After really heated argument in QQ,we think flaminca should stay current version.And if this nerf is not enough,we can adjust them later. And Primal Savagery: damage a NON-CULTIST ally 3 damage,and then look at 2 random bronze cultist, play 1 and strengthen it 1. Raging Bear: reduce to 13 By the way,you can code Svalblod: Damage all loyal units in your hand and deck by 2, then Strengthen them by 2. Move any cards with 2 power or lower from your deck to your graveyard. If it was in your hand, set it's power to 1 instead. So the adjustments in #569 are half passed.Corsair,Dimun Warship,Craite Whaler are non-diy cards,we perfer not to adjust them except them are too weak or too powerful.

Clear enough for this patch, but for the other one corsair was a 3 pts card in beta so I don't understand why this excuse works in that case.

**Comment by Pippow** [comment]
@The-last-Iris I coded everything besides the translations in case something changes

**Comment by Pippow** [comment]
Also I won't back off on the corsair topic, it was at 3 for a reason in Beta

**Comment by The-last-Iris** [comment]
> @The-last-Iris I coded everything besides the translations in case something changes

siren:每当场上降下“倾盆大雨”时，复活自身到友方随机排。
Primal Savagery: 对一个非“诅咒生物”友方单位造成3点伤害，随后检视牌组中2张“呓语”牌，选择打出其中1张，并使其获得1点强化。
Berserker Marauder：场上每有一个受伤单位则获得1点增益，若该受伤单位为“诅咒生物”，则获得2点增益。
Svalblod: 对牌组中所有单位造成2点伤害，随后强化2点。若该单位位于牌组中且战力不大于2，直接进入墓地；若该单位位于手牌且战力不大于2，战力被设为1.

**Comment by The-last-Iris** [comment]
@neal2018 it is okay

**Comment by The-last-Iris** [comment]
> @The-last-Iris I coded everything besides the translations in case something changes

Primal Savagery: 对一个非“诅咒生物”友方单位造成3点伤害，随后检视牌组中2张“呓语”牌，选择打出其中1张，并使其获得1点强化。
I found that this translation text haven't been updating,have you already finish all the text?

**Comment by Pippow** [comment]
> > @The-last-Iris I coded everything besides the translations in case something changes
> 
> Primal Savagery: 对一个非“诅咒生物”友方单位造成3点伤害，随后检视牌组中2张“呓语”牌，选择打出其中1张，并使其获得1点强化。 I found that this translation text haven't been updating,have you already finish all the text?

Not yet, but will finish it today

**Comment by neal2018** [comment]
ok, I will merge this once the (Chinese) translation is added

**Comment by The-last-Iris** [comment]
> > > @The-last-Iris I coded everything besides the translations in case something changes
> > 
> > 
> > Primal Savagery: 对一个非“诅咒生物”友方单位造成3点伤害，随后检视牌组中2张“呓语”牌，选择打出其中1张，并使其获得1点强化。 I found that this translation text haven't been updating,have you already finish all the text?
> 
> Not yet, but will finish it today

Thank you for your help,we can't wait to see new rain SK

**Comment by The-last-Iris** [comment]
> ok, I will merge this once the (Chinese) translation is added

By the way,I think that reset mmr per 3 months is reasonable,what is your opinion?

**Comment by Pippow** [comment]
@neal2018 @The-last-Iris before merging I need to understand what happens to a 2pts unit in hand, according to the text it should go to one. Seems odd, should nothing happen to it? Just get damaged by 1? That's why I figured out from the text it should be just strengthen then damage for units in hand, which is simpler but quite a buff.

**Comment by Pippow** [comment]
> > ok, I will merge this once the (Chinese) translation is added
> 
> By the way,I think that reset mmr per 3 months is reasonable,what is your opinion?

I Thik it's a good goal, but I'd rather tie seasons to patches than stricty dates.

**Comment by The-last-Iris** [comment]
> > > ok, I will merge this once the (Chinese) translation is added
> > 
> > 
> > By the way,I think that reset mmr per 3 months is reasonable,what is your opinion?
> 
> I Thik it's a good goal, but I'd rather tie seasons to patches than stricty dates.

Alright,I will ask QQ if they are approved

**Comment by Pippow** [comment]
@The-last-Iris @neal2018 it's ready to merge except for polish translation

**Comment by The-last-Iris** [comment]
> @The-last-Iris @neal2018 it's ready to merge except for polish translation

There is something wrong with Svalblod,when the Heymaey protector in your hand,play Svalblod directly will make protector goes 4 str.

**Comment by The-last-Iris** [comment]
> @The-last-Iris @neal2018 it's ready to merge except for polish translation

And the Chinese translation for Berserker Marauder should be replaced：场上每有一个受伤单位或“诅咒生物”则获得1点增益，若该受伤单位为“诅咒生物”，则获得2点增益。
the Chinese translation for Primal Savagery should be replaced：对一个非“呓语”友方单位造成3点伤害，随后检视牌组中2张“呓语”牌，选择打出其中1张，并使其获得1点强化。

**Comment by The-last-Iris** [comment]
@Pippow We think the rain SK is still OP.So we want to nerf some cards.
Svalblod: not aim to Golden anymore.(So Sig can't be send to graveyard directly)
Vabjorn: return to 11 str,damage ONLY one unit(maybe we can diy some new card,keep old card still,and it is really OP in rain SK)
Crow Clan Druid: spawn a crow RIGHT side.(left side crow makes Greatsword lose his job,the crow can interact with longship and Savagrey in the same time,it is too comprehensive in general use)

**Comment by The-last-Iris** [comment]
And Brawler is OP too,but QQ haven't discuss a good idea to nerf it,maybe you can give us some advice.

**Comment by Pippow** [comment]
> @Pippow We think the rain SK is still OP.So we want to nerf some cards.
> Svalblod: not aim to Golden anymore.(So Sig can't be send to graveyard directly)
> Vabjorn: return to 11 str,damage ONLY one unit(maybe we can diy some new card,keep old card still,and it is really OP in rain SK)

> Crow Clan Druid: spawn a crow RIGHT side.(left side crow makes Greatsword lose his job,the crow can interact with longship and Savagrey in the same time,it is too comprehensive in general use)

Sorry for anewseringlate. Honestly I don't like any of those changes because they don't aim at rain cards and restrict deck building possibilities. I have played shipless crows after the nerf and it's now a tier 2, without Sigvald on svalblod or ships to kill the crows, the suggested changes kills 2 archetypes in a blow. Also would make further Svalblod a rain only leader. But  I'll pass to our reviewers.

**Comment by Pippow** [comment]
> And Brawler is OP too,but QQ haven't discuss a good idea to nerf it,maybe you can give us some advice.

Well I suggest reducing damage, 8 really kills most bronze engines. I'd make it random ticks for starters and reduce it to 6 probably.

**Comment by The-last-Iris** [comment]
> > And Brawler is OP too,but QQ haven't discuss a good idea to nerf it,maybe you can give us some advice.
> 
> Well I suggest reducing damage, 8 really kills most bronze engines. I'd make it random ticks for starters and reduce it to 6 probably.



> > @Pippow We think the rain SK is still OP.So we want to nerf some cards.
> > Svalblod: not aim to Golden anymore.(So Sig can't be send to graveyard directly)
> > Vabjorn: return to 11 str,damage ONLY one unit(maybe we can diy some new card,keep old card still,and it is really OP in rain SK)
> 
> > Crow Clan Druid: spawn a crow RIGHT side.(left side crow makes Greatsword lose his job,the crow can interact with longship and Savagrey in the same time,it is too comprehensive in general use)
> 
> Sorry for anewseringlate. Honestly I don't like any of those changes because they don't aim at rain cards and restrict deck building possibilities. I have played shipless crows after the nerf and it's now a tier 2, without Sigvald on svalblod or ships to kill the crows, the suggested changes kills 2 archetypes in a blow. Also would make further Svalblod a rain only leader. But I'll pass to our reviewers.

You can try to build a rain SK deck without Sig,in fact I did,and use it more than 10 times.I found rain SK got reasonable win-rate without Sig.So I believe the problem is Sig can be triggered easily.As for Vabjorn,in most condition,it can be 20+ point in rain SK.
Crow Clan Druid just make Greatsword appearance rate lower,I think diy card shouldn't take the places for old cards.

**Comment by Pippow** [comment]
> > > And Brawler is OP too,but QQ haven't discuss a good idea to nerf it,maybe you can give us some advice.
> > 
> > 
> > Well I suggest reducing damage, 8 really kills most bronze engines. I'd make it random ticks for starters and reduce it to 6 probably.
> 
> > > @Pippow We think the rain SK is still OP.So we want to nerf some cards.
> > > Svalblod: not aim to Golden anymore.(So Sig can't be send to graveyard directly)
> > > Vabjorn: return to 11 str,damage ONLY one unit(maybe we can diy some new card,keep old card still,and it is really OP in rain SK)
> > 
> > 
> > > Crow Clan Druid: spawn a crow RIGHT side.(left side crow makes Greatsword lose his job,the crow can interact with longship and Savagrey in the same time,it is too comprehensive in general use)
> > 
> > 
> > Sorry for anewseringlate. Honestly I don't like any of those changes because they don't aim at rain cards and restrict deck building possibilities. I have played shipless crows after the nerf and it's now a tier 2, without Sigvald on svalblod or ships to kill the crows, the suggested changes kills 2 archetypes in a blow. Also would make further Svalblod a rain only leader. But I'll pass to our reviewers.
> 
> You can try to build a rain SK deck without Sig,in fact I did,and use it more than 10 times.I found rain SK got reasonable win-rate without Sig.So I believe the problem is Sig can be triggered easily.As for Vabjorn,in most condition,it can be 20+ point in rain SK. Crow Clan Druid just make Greatsword appearance rate lower,I think diy card shouldn't take the places for old cards.

Greatswords happen to be a great counter to crow clan druids. They have also been the number 1 deck for the entire last part of the beta and many people are sick of them. I think on the other hand that we should give players deckbuilding options: currently GS wins as much as ships with crows so I see no issue there. Ships used to work well with cursed too before the corsair nerf and it was fine.

On Vabjorn I can see it's power, but if you're expecting it it's not that hard to play around. I beat Toussaint99's version before the nerf with a deck that played big units and 0 boosts. Rain has no movement so it's easy to play around it.

So, to reassume, QQ is positive it wants to make Svalblod a rain only leader? I personally have found several fun decks (shipless crows, self damage, discard, etc.) that would become unplayable if golds are not hit anymore

**Comment by The-last-Iris** [comment]
> > > > And Brawler is OP too,but QQ haven't discuss a good idea to nerf it,maybe you can give us some advice.
> > > 
> > > 
> > > Well I suggest reducing damage, 8 really kills most bronze engines. I'd make it random ticks for starters and reduce it to 6 probably.
> > 
> > 
> > > > @Pippow We think the rain SK is still OP.So we want to nerf some cards.
> > > > Svalblod: not aim to Golden anymore.(So Sig can't be send to graveyard directly)
> > > > Vabjorn: return to 11 str,damage ONLY one unit(maybe we can diy some new card,keep old card still,and it is really OP in rain SK)
> > > 
> > > 
> > > > Crow Clan Druid: spawn a crow RIGHT side.(left side crow makes Greatsword lose his job,the crow can interact with longship and Savagrey in the same time,it is too comprehensive in general use)
> > > 
> > > 
> > > Sorry for anewseringlate. Honestly I don't like any of those changes because they don't aim at rain cards and restrict deck building possibilities. I have played shipless crows after the nerf and it's now a tier 2, without Sigvald on svalblod or ships to kill the crows, the suggested changes kills 2 archetypes in a blow. Also would make further Svalblod a rain only leader. But I'll pass to our reviewers.
> > 
> > 
> > You can try to build a rain SK deck without Sig,in fact I did,and use it more than 10 times.I found rain SK got reasonable win-rate without Sig.So I believe the problem is Sig can be triggered easily.As for Vabjorn,in most condition,it can be 20+ point in rain SK. Crow Clan Druid just make Greatsword appearance rate lower,I think diy card shouldn't take the places for old cards.
> 
> Greatswords happen to be a great counter to crow clan druids. They have also been the number 1 deck for the entire last part of the beta and many people are sick of them. I think on the other hand that we should give players deckbuilding options: currently GS wins as much as ships with crows so I see no issue there. Ships used to work well with cursed too before the corsair nerf and it was fine.
> 
> On Vabjorn I can see it's power, but if you're expecting it it's not that hard to play around. I beat Toussaint99's version before the nerf with a deck that played big units and 0 boosts. Rain has no movement so it's easy to play around it.
> 
> So, to reassume, QQ is positive it wants to make Svalblod a rain only leader? I personally have found several fun decks (shipless crows, self damage, discard, etc.) that would become unplayable if golds are not hit anymore

We don't want to kill ANY archetype,we just want to make the environment diversify.Vabjorn gets too high win-rate and it almost appears in every SK deck,the same as Sig.I think the core status of shipless crows, self damage, discard is not Sig,so if golds are not hit won't kill shipless crows, self damage, discard,etc.

**Comment by Pippow** [comment]
> > > > > And Brawler is OP too,but QQ haven't discuss a good idea to nerf it,maybe you can give us some advice.
> > > > 
> > > > 
> > > > Well I suggest reducing damage, 8 really kills most bronze engines. I'd make it random ticks for starters and reduce it to 6 probably.
> > > 
> > > 
> > > > > @Pippow We think the rain SK is still OP.So we want to nerf some cards.
> > > > > Svalblod: not aim to Golden anymore.(So Sig can't be send to graveyard directly)
> > > > > Vabjorn: return to 11 str,damage ONLY one unit(maybe we can diy some new card,keep old card still,and it is really OP in rain SK)
> > > > 
> > > > 
> > > > > Crow Clan Druid: spawn a crow RIGHT side.(left side crow makes Greatsword lose his job,the crow can interact with longship and Savagrey in the same time,it is too comprehensive in general use)
> > > > 
> > > > 
> > > > Sorry for anewseringlate. Honestly I don't like any of those changes because they don't aim at rain cards and restrict deck building possibilities. I have played shipless crows after the nerf and it's now a tier 2, without Sigvald on svalblod or ships to kill the crows, the suggested changes kills 2 archetypes in a blow. Also would make further Svalblod a rain only leader. But I'll pass to our reviewers.
> > > 
> > > 
> > > You can try to build a rain SK deck without Sig,in fact I did,and use it more than 10 times.I found rain SK got reasonable win-rate without Sig.So I believe the problem is Sig can be triggered easily.As for Vabjorn,in most condition,it can be 20+ point in rain SK. Crow Clan Druid just make Greatsword appearance rate lower,I think diy card shouldn't take the places for old cards.
> > 
> > 
> > Greatswords happen to be a great counter to crow clan druids. They have also been the number 1 deck for the entire last part of the beta and many people are sick of them. I think on the other hand that we should give players deckbuilding options: currently GS wins as much as ships with crows so I see no issue there. Ships used to work well with cursed too before the corsair nerf and it was fine.
> > On Vabjorn I can see it's power, but if you're expecting it it's not that hard to play around. I beat Toussaint99's version before the nerf with a deck that played big units and 0 boosts. Rain has no movement so it's easy to play around it.
> > So, to reassume, QQ is positive it wants to make Svalblod a rain only leader? I personally have found several fun decks (shipless crows, self damage, discard, etc.) that would become unplayable if golds are not hit anymore
> 
> We don't want to kill ANY archetype,we just want to make the environment diversify.Vabjorn gets too high win-rate and it almost appears in every SK deck,the same as Sig.I think the core status of shipless crows, self damage, discard is not Sig,so if golds are not hit won't kill shipless crows, self damage, discard,etc.

The issue for cursed for instance is it needs those golds to be damaged to buff the berserker maraudeur. Also the archetype relies on Sigvald for extra cursed value, may very well kill it.
On shipless crows it's a bit less obvious but if you don't draw the druids or if the opponent has control you are pretty much dead. Not to mention some versions run renew for a nice 24 second Olaf or Triss, which will hurt the deck.
I don't see an issue with Sigvald being in every Svalblod deck, feels natural and he is the only good discard target beside sirens, forcing you to play rain IMO.
As far as I know Vabjorn is mostly played in rain and is pretty meh in other decks, especially since I see lots of boosts and even armor on the ladder. I think the rain nerfs should focus on the rain cards.
Anyhow, if QQ is positive those changes are needed I can code them.

**Comment by The-last-Iris** [comment]
> > > > > > And Brawler is OP too,but QQ haven't discuss a good idea to nerf it,maybe you can give us some advice.
> > > > > 
> > > > > 
> > > > > Well I suggest reducing damage, 8 really kills most bronze engines. I'd make it random ticks for starters and reduce it to 6 probably.
> > > > 
> > > > 
> > > > > > @Pippow We think the rain SK is still OP.So we want to nerf some cards.
> > > > > > Svalblod: not aim to Golden anymore.(So Sig can't be send to graveyard directly)
> > > > > > Vabjorn: return to 11 str,damage ONLY one unit(maybe we can diy some new card,keep old card still,and it is really OP in rain SK)
> > > > > 
> > > > > 
> > > > > > Crow Clan Druid: spawn a crow RIGHT side.(left side crow makes Greatsword lose his job,the crow can interact with longship and Savagrey in the same time,it is too comprehensive in general use)
> > > > > 
> > > > > 
> > > > > Sorry for anewseringlate. Honestly I don't like any of those changes because they don't aim at rain cards and restrict deck building possibilities. I have played shipless crows after the nerf and it's now a tier 2, without Sigvald on svalblod or ships to kill the crows, the suggested changes kills 2 archetypes in a blow. Also would make further Svalblod a rain only leader. But I'll pass to our reviewers.
> > > > 
> > > > 
> > > > You can try to build a rain SK deck without Sig,in fact I did,and use it more than 10 times.I found rain SK got reasonable win-rate without Sig.So I believe the problem is Sig can be triggered easily.As for Vabjorn,in most condition,it can be 20+ point in rain SK. Crow Clan Druid just make Greatsword appearance rate lower,I think diy card shouldn't take the places for old cards.
> > > 
> > > 
> > > Greatswords happen to be a great counter to crow clan druids. They have also been the number 1 deck for the entire last part of the beta and many people are sick of them. I think on the other hand that we should give players deckbuilding options: currently GS wins as much as ships with crows so I see no issue there. Ships used to work well with cursed too before the corsair nerf and it was fine.
> > > On Vabjorn I can see it's power, but if you're expecting it it's not that hard to play around. I beat Toussaint99's version before the nerf with a deck that played big units and 0 boosts. Rain has no movement so it's easy to play around it.
> > > So, to reassume, QQ is positive it wants to make Svalblod a rain only leader? I personally have found several fun decks (shipless crows, self damage, discard, etc.) that would become unplayable if golds are not hit anymore
> > 
> > 
> > We don't want to kill ANY archetype,we just want to make the environment diversify.Vabjorn gets too high win-rate and it almost appears in every SK deck,the same as Sig.I think the core status of shipless crows, self damage, discard is not Sig,so if golds are not hit won't kill shipless crows, self damage, discard,etc.
> 
> The issue for cursed for instance is it needs those golds to be damaged to buff the berserker maraudeur. Also the archetype relies on Sigvald for extra cursed value, may very well kill it. On shipless crows it's a bit less obvious but if you don't draw the druids or if the opponent has control you are pretty much dead. Not to mention some versions run renew for a nice 24 second Olaf or Triss, which will hurt the deck. I don't see an issue with Sigvald being in every Svalblod deck, feels natural and he is the only good discard target beside sirens, forcing you to play rain IMO. As far as I know Vabjorn is mostly played in rain and is pretty meh in other decks, especially since I see lots of boosts and even armor on the ladder. I think the rain nerfs should focus on the rain cards. Anyhow, if QQ is positive those changes are needed I can code them.

You can just see the Eskel and Vabjorn,Vabjorn is far more powerful.
And if we don't nerf Svalblod affect,at least we should nerf Svalblod str,11+2 makes opposite hard to deal with sig,you still fall behind 5 even if you play vesemir and mardroeme.

**Comment by The-last-Iris** [comment]
I think the rain nerfs should focus on the rain cards. 
In fact,brawler got a reasonable point,for you have to play it in rain,but I just think it shouldn't got much damage.

**Pull request merged**
