### PR TITLE
New cards: Lyrians

### PR DESCRIPTION
**Pull request by Pippow**
Hi guys, here are the remaining 3 last cards that were approved from the July review process.

- Lyrian Scytheman: strength 5 => 9, effect changed to "Deploy: Boost a unit in your deck by 4."
- Lyrian Cavalry: new bronze Lyrian soldier, 7pts, "Deploy: choose a unit from your deck and boost self by the amount that unit is boosted."
- Lyrian Arbalest: new bronze Lyrian soldier, "Deploy: Damage an Ennemy unit with lower Power than self, by the difference between the two card's Power."

### CODE REVIEW

**Comment by Pippow** [comment]
@neal2018 hi, do you have an idea why the WebGL build fails? It happenned to me in the past but just relaunching it solved it last time. Looking it up on Google it seems that it's using too many ressources.

**Comment by neal2018** [comment]
I am not sure what happened, but why we have thousands of changes on `src/Cynthia.Card/src/Cynthia.Card.Server/Locales/`?

image

Looks like you changed the indent from 4 to 2? I suggest we keep using 4 as usual if it is a mistake.

**Comment by Pippow** [comment]
> I am not sure what happened, but why we have thousands of changes on `src/Cynthia.Card/src/Cynthia.Card.Server/Locales/`?
> 
> image
> Looks like you changed the indent from 4 to 2? I suggest we keep using 4 as usual if it is a mistake.
Yes, it's the indent that changed, for some reason whenever I touch anything at the end of the files, the indent switches to 2, it's pretty annoying, will try to fix it. Any advice?

**Comment by neal2018** [comment]
If you are using vscode, you can configure the indent on bottom right corner

**Comment by Pippow** [comment]
> If you are using vscode, you can configure the indent on bottom right corner

Thanks, I'm on visual studio community though, I don't see the option in the corner
image
Anyway I found a tutorial to set the JSON default indent to 4 and not 2, so everything should be ready to merge (I tested the patch locally, works fine, seems very strong by the way)

**Comment by neal2018** [comment]
The community decided to merge this change after the October tournament. c.c. @NPC-YFY

**Comment by neal2018** [comment]
FYI, `src/Cynthia.Card/src/Cynthia.Card.Server/Locales/pl.json` still has wrong indent

**Comment by NPC-YFY** [comment]
@neal2018

**Comment by neal2018** [comment]
Thanks for the work!

**Pull request merged**
