### PR TITLE
Discard balance patch

### PR DESCRIPTION
**Pull request by Pippow**
Balance patch:
- Heymaey Skald: buff by 2 => buff by 1 and 9 power => 8 power
- Lady of the Lake: 25 => 23
- Ciri Nova: 22 => 23
- Pillagers no longer buff units on the board (only deck and hand)

### CODE REVIEW

**Comment by fraloow** [comment]
Thank you for your contribution.This paragraph is a machine translation may not be accurate

1. I support Heymaey Skald: buff by 2 => buff by 1. With the addition of new cards, this card should change, but it seems unnecessary to change it from 9 power => 8 power. If the goal is to compare it to other factions' similar cards, it would be best to keep the power as it is and consider the quality and quantity of cards with different tags.
2. It seems that you want to synchronize the power of Lady of the Lake and Nova. Although Lady of the Lake is currently a card of concern, its win rate is still acceptable. Changing it from 25 => 23 has a small impact on gameplay, and one point to consider is that having it be less than 25 points might prevent it from being destroyed by Igni, which removes an element of strategy. Therefore, it is also best to keep Lady of the Lake and Nova as they are now.

**Comment by fraloow** [comment]
Thank you for your contribution.

1. I support Heymaey Skald: buff by 2 => buff by 1. With the addition of new cards, this card should change, but it seems unnecessary to change it from 9 power => 8 power. If the goal is to compare it to other factions' similar cards, it would be best to keep the power as it is and consider the quality and quantity of cards with different tags.

2. It seems that you want to synchronize the power of Lady of the Lake and Nova. Although Lady of the Lake is currently a card of concern, its win rate is still acceptable. Changing it from 25 => 23 has a small impact on gameplay, and one point to consider is that having it be less than 25 points might prevent it from being destroyed by Igni, which removes an element of strategy. Therefore, it is also best to keep Lady of the Lake and Nova as they are now.

**Comment by Pippow** [comment]
> Thank you for your contribution.
> 
> 1. I support Heymaey Skald: buff by 2 => buff by 1. With the addition of new cards, this card should change, but it seems unnecessary to change it from 9 power => 8 power. If the goal is to compare it to other factions' similar cards, it would be best to keep the power as it is and consider the quality and quantity of cards with different tags.
> 2. It seems that you want to synchronize the power of Lady of the Lake and Nova. Although Lady of the Lake is currently a card of concern, its win rate is still acceptable. Changing it from 25 => 23 has a small impact on gameplay, and one point to consider is that having it be less than 25 points might prevent it from being destroyed by Igni, which removes an element of strategy. Therefore, it is also best to keep Lady of the Lake and Nova as they are now.

Thanks for the feedback, this is already the product of various converging opinions on the Discord and I'd like to add as many people as possible to the discussion. I think some QG nerf is needed but I'm open to changing my mind about how to do it. Same about the lady Nerf, if you abosolutely hate it we can do without.

1. SanguineRose on the Discord suggested this change. The reasoning is that a 9pts Skald will block a scorch/Ingi on a fully strenghtened Queensguard row, so nerfing it to 8 adds some strategy.
2. The reason why Lady has an acceptable winrate is because it is played in both good and bad decks, which makes its stats confusing. The main archetype that is too strong because of it (IMO) is Reveal, which it enables to be very good in a short round 3. Generally, Lady is too much above the curve for big gold finishers and makes many cards obsolete like Xavier, Nova, Bloody Baron etc. and this is an attempt to bring it to their powerlevel. Generally speaking, 25 feels too much for a neutral card with limited deckbuilding cost. Hyperthinning is already a good strat even without Lady. The same thing about Igni was said when Nova was nerfed, but in the end Igni into the 25gold is a very niche and rare scenario, you need last say, might have a better target earlier, and can do it with a 22/23pts nova/lady as long as it's not played on an empty row.

**Comment by fraloow** [comment]
1. Regarding the Heymaey Skald, the reason for weakening the third card in order for the first card to be countered by the second card is not very sufficient. It is more appropriate to simply weaken the first card, and the poet's points have already been reduced (buff by 2 => buff by 1).
2. As for the Lady of the Lake, compared to other finishers, the timing of playing and the number of countermeasures for the Lake Lady are more strict. It also makes up for some of the shortcomings that the deck should have. Although I think that neutral finishers should be weaker, and can try 23 points, with the expansion of new card points and its popularity, there may be more controversy. It may be more appropriate to balance it with more cards at the same time.

**Comment by fraloow** [comment]
I resubmitted a pr to include Heymaey Skald and other balances, any suggestions or ideas from your side?

Enhancement
Amnesty: Return 1 non-spy bronze/silver enemy unit to the opponent's hand -> Return 1 bronze/silver enemy unit to the opponent's hand and set its battle power to 1

Weakening:
Heymaey Skald: buff 2 -> buff 1
Krtulis: below 6 -> below 5

Bug fixes:
Fix the issue that playing Fauve will summon Roach

Regarding other discussions, the positioning of Artorius Vigo and Knut is too similar to that of Operator. I think these two cards are advanced versions of the operator, which is a bit unhealthy. I don't know what your thoughts are, it's just a discussion.

**Comment by Pippow** [comment]
> I resubmitted a pr to include Heymaey Skald and other balances, any suggestions or ideas from your side?
> 
> Enhancement Amnesty: Return 1 non-spy bronze/silver enemy unit to the opponent's hand -> Return 1 bronze/silver enemy unit to the opponent's hand and set its battle power to 1
> 
> Weakening: Heymaey Skald: buff 2 -> buff 1 Krtulis: below 6 -> below 5
> 
> Bug fixes: Fix the issue that playing Fauve will summon Roach
> 
> Regarding other discussions, the positioning of Artorius Vigo and Knut is too similar to that of Operator. I think these two cards are advanced versions of the operator, which is a bit unhealthy. I don't know what your thoughts are, it's just a discussion.

Thanks, I guess we can just keep one of the 2 PRs then, I wanted to do a quick fix of QGs to appease the Discord, but we can do a more complete balance patch, even better!

- I'm a bit confused about the Keltullis nerf, I barely see it on the ladder and I wonder why he needs a nerf. 
- I think Amnesty is still way too weak, it's a worst artefact compression that gives the opponent card advantage. I have seen different suggestions on the discord: "destroy a bronze or silver adjacent to a spy", or "send a bronze or silver ennemy to the opponent's deck"
- The Fauve summoning Roach is not a bug as far as I know. Roach gets summoned whenever a gold card enters the game, for instance getting Cerys out will pull out Roach. So if you change that it's more balancing than fixing a bug. When Fauve came out I thought it would be OP, but in the end it's not that strong, and the Roach interaction is not game-breaking so I think we can just leave it as it is.
- Vigo and Knut are faction-specific Operator's equivalents. I really love the fact that you buffed operator to 7, it makes Knut and Vigo less necessary, but queensguards for instance run both. I don't really know what to do with Vigo and Knut, someone suggested they should have pre-determined options (like you always choose from the 3 same units)

Beyond that, I see you left the pillager and Lady nerfs out, as well as the Nova buff, is that on purpose? Or shall we keep 2 PRs? I can do without the Lady nerf, the Nova buff is pretty irrelevant but feels good, but the pillager one I feel is important.

**Comment by Pippow** [comment]
Other changes that were discussed in the Discord to improve Skellige's faction diversity:

To compensate for the corsair nerf:
- Buff the Dimun Light Longhsip to deal 5 damage instead of 4
- Berserker Marauders: buff by 1 for each cursed and/or damaged allies (damaged cursed units count +2)
To bring veterans back
- Make Veterans a soldier again (this needs discussion because it is a very big buff)

**Comment by fraloow** [comment]
> > I resubmitted a pr to include Heymaey Skald and other balances, any suggestions or ideas from your side?
> > Enhancement Amnesty: Return 1 non-spy bronze/silver enemy unit to the opponent's hand -> Return 1 bronze/silver enemy unit to the opponent's hand and set its battle power to 1
> > Weakening: Heymaey Skald: buff 2 -> buff 1 Krtulis: below 6 -> below 5
> > Bug fixes: Fix the issue that playing Fauve will summon Roach
> > Regarding other discussions, the positioning of Artorius Vigo and Knut is too similar to that of Operator. I think these two cards are advanced versions of the operator, which is a bit unhealthy. I don't know what your thoughts are, it's just a discussion.
> 
> Thanks, I guess we can just keep one of the 2 PRs then, I wanted to do a quick fix of QGs to appease the Discord, but we can do a more complete balance patch, even better!
> 
> * I'm a bit confused about the Keltullis nerf, I barely see it on the ladder and I wonder why he needs a nerf.
> * I think Amnesty is still way too weak, it's a worst artefact compression that gives the opponent card advantage. I have seen different suggestions on the discord: "destroy a bronze or silver adjacent to a spy", or "send a bronze or silver ennemy to the opponent's deck"
> * The Fauve summoning Roach is not a bug as far as I know. Roach gets summoned whenever a gold card enters the game, for instance getting Cerys out will pull out Roach. So if you change that it's more balancing than fixing a bug. When Fauve came out I thought it would be OP, but in the end it's not that strong, and the Roach interaction is not game-breaking so I think we can just leave it as it is.
> * Vigo and Knut are faction-specific Operator's equivalents. I really love the fact that you buffed operator to 7, it makes Knut and Vigo less necessary, but queensguards for instance run both. I don't really know what to do with Vigo and Knut, someone suggested they should have pre-determined options (like you always choose from the 3 same units)
> 
> Beyond that, I see you left the pillager and Lady nerfs out, as well as the Nova buff, is that on purpose? Or shall we keep 2 PRs? I can do without the Lady nerf, the Nova buff is pretty irrelevant but feels good, but the pillager one I feel is important.

1. Regarding Keltullis, although it is not used much, there is a suggestion to weaken it in this community, so we will observe the data after slightly weakening it.
2. Regarding Amnesty, I actually want it to cooperate with Toussaint Knight Errant, not too strong, the effect of "destroy a bronze or silver adjacent to a spy", and "send a bronze or silver enemy to the opponent's deck" may be interesting and could be a new DIY card.
3. Regarding Roach, the description here has always been "played", but Roach now has the effect of "appearing" because it was designed to allow Enhyr to trigger Roach when playing a gold card. There is currently no suitable solution at the code level, But Fauve plus it may be a bit too much
4. I think Vigo and Knut are not healthy and dangerous, it is best to redo them. The operator was changed by another guys
5. Pillagers no longer buff units on the board (only deck and hand)  I can add it in. And I have a new idea: strengthen the graveyard when played, and strengthen the deck when discarded.
6. I want to keep Lady and Nova as they are.
7. Is it Dimun warship rather than Dimun Light Longship? Making Veterans a soldier again is absolutely not possible. As for Dimun warship and Berserker Marauders, they can be considered, but there are currently no plans to make changes.

**Comment by Pippow** [comment]
> 



> > > I resubmitted a pr to include Heymaey Skald and other balances, any suggestions or ideas from your side?
> > > Enhancement Amnesty: Return 1 non-spy bronze/silver enemy unit to the opponent's hand -> Return 1 bronze/silver enemy unit to the opponent's hand and set its battle power to 1
> > > Weakening: Heymaey Skald: buff 2 -> buff 1 Krtulis: below 6 -> below 5
> > > Bug fixes: Fix the issue that playing Fauve will summon Roach
> > > Regarding other discussions, the positioning of Artorius Vigo and Knut is too similar to that of Operator. I think these two cards are advanced versions of the operator, which is a bit unhealthy. I don't know what your thoughts are, it's just a discussion.
> > 
> > 
> > Thanks, I guess we can just keep one of the 2 PRs then, I wanted to do a quick fix of QGs to appease the Discord, but we can do a more complete balance patch, even better!
> > 
> > * I'm a bit confused about the Keltullis nerf, I barely see it on the ladder and I wonder why he needs a nerf.
> > * I think Amnesty is still way too weak, it's a worst artefact compression that gives the opponent card advantage. I have seen different suggestions on the discord: "destroy a bronze or silver adjacent to a spy", or "send a bronze or silver ennemy to the opponent's deck"
> > * The Fauve summoning Roach is not a bug as far as I know. Roach gets summoned whenever a gold card enters the game, for instance getting Cerys out will pull out Roach. So if you change that it's more balancing than fixing a bug. When Fauve came out I thought it would be OP, but in the end it's not that strong, and the Roach interaction is not game-breaking so I think we can just leave it as it is.
> > * Vigo and Knut are faction-specific Operator's equivalents. I really love the fact that you buffed operator to 7, it makes Knut and Vigo less necessary, but queensguards for instance run both. I don't really know what to do with Vigo and Knut, someone suggested they should have pre-determined options (like you always choose from the 3 same units)
> > 
> > Beyond that, I see you left the pillager and Lady nerfs out, as well as the Nova buff, is that on purpose? Or shall we keep 2 PRs? I can do without the Lady nerf, the Nova buff is pretty irrelevant but feels good, but the pillager one I feel is important.
> 
> 1. Regarding Keltullis, although it is not used much, there is a suggestion to weaken it in this community, so we will observe the data after slightly weakening it.
> 2. Regarding Amnesty, I actually want it to cooperate with Toussaint Knight Errant, not too strong, the effect of "destroy a bronze or silver adjacent to a spy", and "send a bronze or silver enemy to the opponent's deck" may be interesting and could be a new DIY card.
> 3. Regarding Roach, the description here has always been "played", but Roach now has the effect of "appearing" because it was designed to allow Enhyr to trigger Roach when playing a gold card. There is currently no suitable solution at the code level, But Fauve plus it may be a bit too much
> 4. I think Vigo and Knut are not healthy and dangerous, it is best to redo them. The operator was changed by another guys
> 5. Pillagers no longer buff units on the board (only deck and hand)  I can add it in.
> 6. I want to keep Lady and Nova as they are.
> 7. Is it Dimun warship rather than Dimun Light Longship? Making Veterans a soldier again is absolutely not possible. As for Dimun warship and Berserker Marauders, they can be considered, but there are currently no plans to make changes.

1. Ok, let's try it. I still have no idea what a good Keltullis deks liiks like though^^
2. Oh, I finally understand the purpose of the card, that's interesting, ok, let's gor for what you said
3. I see how it works. Anyway here are Fauve stats: Number of games: 812 Wins: 361 Losses: 439 Draws: 12 Winning percentage: 44.46%, I don't think Fauve into Roach is an issue, but I'm a bit surprised as it looks very strong on paper. Anyway I don't think we need to nerf that
4. I agree about Vigo, amplifies all the strongest NG decks (Handbuff, Alchemy, Reveal etc.). Knut seems less dangerous to me. Its low tempo and lack of targets as good as say, viper witchers, mean that it's only really useful with Queensguards; which in my opinion needed such a card as otherwise you're too susecptible to graveyard hate. The rest of the QG package needs to be tuned down but Vigo is ok, I think, especially since unlike Vigo it has single-use.
5. Thanks, you can copy my code and translations
6. Ok for Lady and Nova for now. But it remains something that is debated often so, as you said, when we do a more comprehensive balance overhaul, we can get back to it. For instance nerfing the reveal cards might be fairer than just nerfing Lady, impacting fewer decks
7. I meant Dimun Warship, my bad, sry. For veterans I don't think making them soldiers is the right solution either, but they have been powercrept, have a bad WR and could use a buff. So if you have other ideas I'm interested. About the dimun warship and the berserker marauders, the reasoning is that the corsair nerf, intended to nerf greatswords, also impacted other decks (axemen, control skellige, berserker marauders mainly), while not doing much to nerf Greatswords. This would be a little buff to those archetypes to compensate for that and encourage more diversity in the Skellige faction. The idea has received some support on the Discord.

**Comment by fraloow** [comment]
OK，Fauve occupies a very precious gold card slot and is only 3 points higher than Roach. This is something I have considered, as a gold card trades for leader tempo, and I hope it can synergize with the new DIY for Dryads in the future. So I will keep it as it is for now and focus on solving the problem with Queensguards.

**Pull request closed without merging**
